name: Generate html

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.4'
        architecture: 'x64'
    - name: Install pipenv
      run: pip install pipenv
    - name: Install requirements
      run: |
        pipenv install,
        pipenv install jupyter_contrib_nbextensions,
        pipenv jupyter contrib nbextension install --user
    - name: Generate html
      run: |
        for i in *.ipynb; do pipenv jupyter nbconvert --to html_embed $i; done,
        mv *.html docs.
